### ISSUE TITLE
[BUG?] Broadcast can not be use

### ISSUE THREAD

**Issue by saltyduckegg** [kmahyyg/ztncui-aio#35]
Hello,

I noticed that there is an enableBroadcast option in the network configuration details. However, even after setting this option to true, it seems that broadcast functionality is still not working as expected.

Could you please provide guidance on how to properly enable and use broadcast functionality with this configuration? Are there additional settings or considerations needed to make broadcasts work?

**Comment by kmahyyg** [comment]
Please kindly provide your environment (device os, os version, software involved) and network topology, docker container startup configuration (`--network=host` or not, and anything else you'd like to include) for further troubleshooting.

And also, please check https://docs.zerotier.com/windows-lan-game if you are on Windows. 

Please also make sure you understand "broadcast domain" concept in computer networking.

If you confirmed everything above, please open a thread on Zerotier Discuss Forum, unless you can confirm the problem is caused by docker.

**Comment by kmahyyg** [comment]
On my side, `--network=host` when starting container, the broadcast is working. Tested against Bonjour/Parsec/Moonlight/Spotify Connect.

**Comment by saltyduckegg** [comment]
Thank you for your response.

I further investigated the issue and found that the problem might be related to the zerotierfix I'm using on my Android device. It appears that the zerotierfix client on Android doesn't support sending broadcast packets. Broadcast packets can be sent and received correctly between Linux and Windows, so the issue seems specific to the Android implementation.
